In [1]:
import pandas as pd
import re
df = pd.read_excel(r"../Input_Files/April_2024_ASP_Pricing_File_032124___Final_File/April 2024 ASP Pricing File 032124.xlsx")

In [64]:
display(df)

,Payment Allowance Limits for Medicare Part B Drugs,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Effective April 1, 2024 through June 30, 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Note 1: Payment allowance limits subject to th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Note 2: The absence or presence of a HCPCS cod...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
822,Q9965,"Locm 100-199mg/ml iodine,1ml",1 ML,1.016,20,NaN,NaN,NaN,NaN,NaN,NaN
823,Q9966,"Locm 200-299mg/ml iodine,1ml",1 ML,0.388,20,NaN,NaN,NaN,NaN,NaN,NaN
824,Q9967,"Locm 300-399mg/ml iodine,1ml",1 ML,0.137,20,NaN,NaN,NaN,NaN,NaN,NaN
825,Q9991,Buprenorph xr 100 mg or less,Less than or equal to 100 MG,1874.902,20,NaN,NaN,NaN,NaN,NaN,NaN
826,Q9992,Buprenorphine xr over 100 mg,Greater than 100 MG,1874.902,20,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
header_row = df[df.iloc[:, 0].str.contains('HCPCS Code', na=False)].index[0] + 1

# Read the data again using the correct header row
df_clean = pd.read_excel(r"../Input_Files/April_2024_ASP_Pricing_File_032124___Final_File/April 2024 ASP Pricing File 032124.xlsx", sheet_name='APR_24_ASP_byHCPCS', header=header_row)

In [66]:
display(df_clean)

,HCPCS Code,Short Description,HCPCS Code Dosage,Payment Limit,Co-insurance Percentage,Vaccine AWP%,Vaccine Limit,Blood AWP%,Blood limit,Clotting Factor,Notes
0,90371,Hep b ig im,1 ML,141.115,20.0,NaN,NaN,NaN,NaN,NaN,NaN
1,90375,Rabies ig im/sc,150 IU,285.652,20.0,NaN,NaN,NaN,NaN,NaN,NaN
2,90377,Rabies ig ht&sol human im/sc,150 IU,250.980,20.0,NaN,NaN,NaN,NaN,NaN,NaN
3,90586,Bcg vaccine intravesical,1 EACH,144.479,20.0,NaN,NaN,NaN,NaN,NaN,NaN
4,90632,Hepa vaccine adult im,1 ML,70.541,20.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
814,Q9965,"Locm 100-199mg/ml iodine,1ml",1 ML,1.016,20.0,NaN,NaN,NaN,NaN,NaN,NaN
815,Q9966,"Locm 200-299mg/ml iodine,1ml",1 ML,0.388,20.0,NaN,NaN,NaN,NaN,NaN,NaN
816,Q9967,"Locm 300-399mg/ml iodine,1ml",1 ML,0.137,20.0,NaN,NaN,NaN,NaN,NaN,NaN
817,Q9991,Buprenorph xr 100 mg or less,Less than or equal to 100 MG,1874.902,20.0,NaN,NaN,NaN,NaN,NaN,NaN
818,Q9992,Buprenorphine xr over 100 mg,Greater than 100 MG,1874.902,20.0,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df_clean.columns

Index(['HCPCS Code', 'Short Description', 'HCPCS Code Dosage', 'Payment Limit',
       'Co-insurance Percentage', 'Vaccine AWP%', 'Vaccine Limit',
       'Blood AWP%', 'Blood limit', 'Clotting Factor', 'Notes'],
      dtype='object')

In [68]:

# Select only the relevant columns
df_extracted = df_clean[['HCPCS Code', 'Payment Limit']]

#Rename the column names
df_extracted = df_extracted.rename(columns={
    'HCPCS Code': 'SVC_CD',
    'Payment Limit': 'FEE'
})


# Add the additional required columns with default values as they are not present in the file
df_extracted['MODIFIER_1'] = ''
df_extracted['MODIFIER_2'] = ''
df_extracted['MODIFIER_3'] = ''
df_extracted['MODIFIER_4'] = ''
df_extracted['AS_OF_DATE'] = ''
df_extracted['AGE_UNIT'] = ''
df_extracted['FROM_AGE'] = ''
df_extracted['THROUGH_AGE'] = ''
df_extracted['PLACE_OF_SERVICE_CODE'] = ''

# Reorder the columns to match the required format
df_extracted = df_extracted[['SVC_CD', 'MODIFIER_1', 'MODIFIER_2', 'MODIFIER_3', 'MODIFIER_4', 'FEE', 'AS_OF_DATE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]

In [69]:
display(df_extracted)

,SVC_CD,MODIFIER_1,MODIFIER_2,MODIFIER_3,MODIFIER_4,FEE,AS_OF_DATE,AGE_UNIT,FROM_AGE,THROUGH_AGE,PLACE_OF_SERVICE_CODE
0,90371,,,,,141.115,,,,,
1,90375,,,,,285.652,,,,,
2,90377,,,,,250.980,,,,,
3,90586,,,,,144.479,,,,,
4,90632,,,,,70.541,,,,,
...,...,...,...,...,...,...,...,...,...,...,...
814,Q9965,,,,,1.016,,,,,
815,Q9966,,,,,0.388,,,,,
816,Q9967,,,,,0.137,,,,,
817,Q9991,,,,,1874.902,,,,,
818,Q9992,,,,,1874.902,,,,,

In [70]:
date_pattern = r"\b\d{6}\b"
    
# Search for the date pattern in the file path
match = re.search(date_pattern, r"../Input_Files/April_2024_ASP_Pricing_File_032124___Final_File/April 2024 ASP Pricing File 032124.xlsx")
    
# Extract and format the date if found
extracted_date = match.group()
formatted_date = f"20{extracted_date[-2:]}-{extracted_date[-4:-2]}-{extracted_date[:-4]}"

In [71]:
# Save the extracted data to a new Excel file
output_file_path = f'../Output_Files/MCare_ASP_{formatted_date}.xlsx'
df_extracted.to_excel(output_file_path, index=False)