In [2]:
import pandas as pd
import re
file_path=r"../Input_Files/CLF 2024 Q2V1/CLFS 2024 Q2V1.xlsx"
df = pd.read_excel(file_path)

In [3]:
display(df)

,2024 Clinical Diagnostic Laboratory Fee Schedule,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,"CPT codes, descriptions and other data only ar...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The Department of Health and Human Services is...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,YEAR,HCPCS,MOD,EFF_DATE,INDICATOR,RATE,SHORTDESC,LONGDESC,EXTENDED LONGDESC
4,2024,0001U,NaN,20240101,N,720,Rbc dna hea 35 ag 11 bld grp,Red blood cell typing,"Red blood cell antigen typing, dna, human eryt..."
...,...,...,...,...,...,...,...,...,...
1999,2024,Q0114,NaN,20240101,N,9.74,Fern test,Fern test,Fern test
2000,2024,Q0115,NaN,20240101,N,25,Post-coital mucous exam,"Post-coital direct, qualitative examinations o...","Post-coital direct, qualitative examinations o..."
2001,2024,U0001,NaN,20240101,N,35.92,2019-ncov diagnostic p,Cdc 2019 novel coronavirus (2019-ncov) real-ti...,Cdc 2019 novel coronavirus (2019-ncov) real-ti...
2002,2024,U0002,NaN,20240101,N,51.31,Covid-19 lab test non-cdc,"2019-ncov coronavirus, sars-cov-2/2019-ncov (c...","2019-ncov coronavirus, sars-cov-2/2019-ncov (c..."
2003,2024,U0002,QW,20240101,N,51.31,Covid-19 lab test non-cdc,"2019-ncov coronavirus, sars-cov-2/2019-ncov (c...","2019-ncov coronavirus, sars-cov-2/2019-ncov (c..."

In [83]:
header_row = df[df.iloc[:, 0].str.contains('YEAR', na=False)].index[0] + 1

# Read the data again using the correct header row
df_clean = pd.read_excel(file_path, header=header_row)

In [84]:
display(df_clean)

,YEAR,HCPCS,MOD,EFF_DATE,INDICATOR,RATE,SHORTDESC,LONGDESC,EXTENDED LONGDESC
0,2024,0001U,NaN,20240101,N,720.00,Rbc dna hea 35 ag 11 bld grp,Red blood cell typing,"Red blood cell antigen typing, dna, human eryt..."
1,2024,0002M,NaN,20240101,N,503.40,Liver dis 10 assays w/ash,"Molecular pathology test for liver disease, in...","Liver disease, ten biochemical assays (alt, a2..."
2,2024,0002U,NaN,20240101,N,25.00,Onc clrct 3 ur metab alg plp,Measurement of substances in urine to predict ...,"Oncology (colorectal), quantitative assessment..."
3,2024,0003M,NaN,20240101,N,503.40,Liver dis 10 assays w/nash,"Molecular pathology test for liver disease, in...","Liver disease, ten biochemical assays (alt, a2..."
4,2024,0003U,NaN,20240101,N,950.00,Onc ovar 5 prtn ser alg scor,Measurement of proteins associated with ovaria...,Oncology (ovarian) biochemical assays of five ...
...,...,...,...,...,...,...,...,...,...
1995,2024,Q0114,NaN,20240101,N,9.74,Fern test,Fern test,Fern test
1996,2024,Q0115,NaN,20240101,N,25.00,Post-coital mucous exam,"Post-coital direct, qualitative examinations o...","Post-coital direct, qualitative examinations o..."
1997,2024,U0001,NaN,20240101,N,35.92,2019-ncov diagnostic p,Cdc 2019 novel coronavirus (2019-ncov) real-ti...,Cdc 2019 novel coronavirus (2019-ncov) real-ti...
1998,2024,U0002,NaN,20240101,N,51.31,Covid-19 lab test non-cdc,"2019-ncov coronavirus, sars-cov-2/2019-ncov (c...","2019-ncov coronavirus, sars-cov-2/2019-ncov (c..."
1999,2024,U0002,QW,20240101,N,51.31,Covid-19 lab test non-cdc,"2019-ncov coronavirus, sars-cov-2/2019-ncov (c...","2019-ncov coronavirus, sars-cov-2/2019-ncov (c..."

In [85]:
columns = df_clean.columns

In [88]:
rate_columns = [col for col in df_clean.columns if col.startswith('RATE')]

# Select the required columns including the first 'RATE' column
df_selected = df_clean[['HCPCS', 'EFF_DATE', rate_columns[0]]]

In [89]:
display(df_selected)

      HCPCS  EFF_DATE    RATE
0     0001U  20240101  720.00
1     0002M  20240101  503.40
2     0002U  20240101   25.00
3     0003M  20240101  503.40
4     0003U  20240101  950.00
...     ...       ...     ...
1995  Q0114  20240101    9.74
1996  Q0115  20240101   25.00
1997  U0001  20240101   35.92
1998  U0002  20240101   51.31
1999  U0002  20240101   51.31

[2000 rows x 3 columns]

In [ ]:
output_path = '../Output_Files/MCare_Clinical_Lab.xlsx'

# Export the DataFrame to an Excel workbook
df_selected.to_excel(output_path, index=False)