In [51]:
import pandas as pd
import os


file_path = "../Monthly_Input_Files/Medi-Cal Rates 12.15.22.xlsx"
date_part = file_path.split(" ")[-1].split(".")  
split_date = '-'.join(date_part[0:3])
month, day, year = split_date.split('-')
if len(year) == 2:
    year = '20' + year
date = f'{year}-{month}-01'

df = pd.read_excel(file_path, skiprows=1)
df_ac= pd.read_excel("../Augment_Codes/Augment Codes.xlsx", skiprows=1)

# Create a directory named after the date if it doesn't exist
if not os.path.exists(f'../Monthly_Output_Files/{date}'):
    os.makedirs(f'../Monthly_Output_Files/{date}')                   
 
# Define new column names based on the data structure in your file
df.columns = ['Proc_Type', 'Proc_Code', 'Procedure_Description', 'Unit_Value',
              'Basic_Rate', 'Child_Rate', 'ER_Rate', 'Conv_Ind', 'ER_Ind',
              'Cutback_Ind', 'Prof_%', 'Rental_Rate', 'Non_Physn_Med_Prac_Ind']
df_ac.columns = ['Proc_Code','Procedure_Description_for_Augmentation', 'Basic_rate', 'Proc_Type']
 
# Remove the $ sign and convert the column to numeric, coerce errors to NaN
df['Basic_Rate'] = pd.to_numeric(df['Basic_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Child_Rate'] = pd.to_numeric(df['Child_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['ER_Rate'] = pd.to_numeric(df['ER_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Rental_Rate'] = pd.to_numeric(df['Rental_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Prof_%'] = pd.to_numeric(df['Prof_%'], errors='coerce').round(2)

merged_df = pd.merge(df, df_ac, how='right', on=['Proc_Code', 'Proc_Type'])
merged_df = merged_df[merged_df['Proc_Type']!= 'J']
#display(merged_df)
df_augment = merged_df
filtered_aug = df_augment[(df_augment['Basic_Rate'] > 0)].copy()
filtered_aug_2 = df_augment[(df_augment['Basic_Rate'] > 0) & (df_augment['Prof_%'] !=0) & (1- df_augment['Prof_%'] > 0)].copy()
    
filtered_aug['FEE']=(filtered_aug['Basic_Rate']*1.4344).round(2)
filtered_aug['MODIFIER_1']=''
filtered_aug['SVC_CD']=filtered_aug['Proc_Code']
    
# Create a technical rate DataFrame
tech_df = filtered_aug_2.copy()
tech_df['FEE'] = (tech_df['Basic_Rate'] * (1 - tech_df['Prof_%']) * 1.4344).round(2)
tech_df['MODIFIER_1'] = 'TC'
tech_df['SVC_CD']=tech_df['Proc_Code']
 
# Append the technical DataFrame to the professional DataFrame
result_df = pd.concat([filtered_aug, tech_df], ignore_index=True)
result_df['AGE_UNIT']=''
result_df['FROM_AGE']=''
result_df['THROUGH_AGE']=''
result_df['PLACE_OF_SERVICE_CODE']=''
final_df_a = result_df[['SVC_CD', 'MODIFIER_1', 'FEE']]
final_df_a.to_csv(f'../Augment_Codes/DNU_Mcal_Augment.{date}.txt', sep='|', index=False)
   
#final_df_a.shape

FileNotFoundError: [Errno 2] No such file or directory: '../Monthly_Input_Files/Medi-Cal Rates 13.15.22.xlsx'

In [26]:
filtered_aug.shape

(6005, 18)

In [27]:
tech_df.shape

(1316, 18)

In [28]:
df_augment.shape

(6306, 15)

In [29]:
merged_df.shape

(6306, 15)

In [30]:
df_ac.shape

(6306, 4)

In [24]:
display(merged_df)

,Proc_Type,Proc_Code,Procedure_Description,Unit_Value,Basic_Rate,Child_Rate,ER_Rate,Conv_Ind,ER_Ind,Cutback_Ind,Prof_%,Rental_Rate,Non_Physn_Med_Prac_Ind,Procedure_Description_for_Augmentation,Basic_rate
0,J,00102,ANESTH REPAIR OF CLEFT LIP,5.42,75.93,NaN,NaN,2.0,0.0,0.0,0.0,0.0,Y,ANESTH REPAIR OF CLEFT LIP,75.93
1,J,00103,ANESTH BLEPHAROPLASTY,4.52,63.33,NaN,NaN,2.0,0.0,0.0,0.0,0.0,Y,ANESTH BLEPHAROPLASTY,63.33
2,J,00104,ANESTH ELECTROSHOCK,3.61,50.58,NaN,NaN,2.0,0.0,0.0,0.0,0.0,Y,ANESTH ELECTROSHOCK,50.58
3,J,00120,ANESTH EAR SURGERY,4.52,63.33,NaN,NaN,2.0,0.0,0.0,0.0,0.0,Y,ANESTH EAR SURGERY,63.33
4,J,00124,ANESTH EAR EXAM,3.61,50.58,NaN,NaN,2.0,0.0,0.0,0.0,0.0,Y,ANESTH EAR EXAM,50.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6301,1,Z7604,EX CORP SHOCK WAVE LITHRPSY OUTPAT FACIL,2000.00,2000.00,NaN,NaN,9.0,0.0,0.0,0.0,0.0,N,EX CORP SHOCK WAVE LITHRPSY OUTPAT FACIL,2000.00
6302,1,Z7606,HYPERBARIC OXY CHMBR 1ST 15MIN ATMOS ABS,19.73,19.73,NaN,NaN,9.0,0.0,0.0,0.0,0.0,Y,HYPERBARIC OXY CHMBR 1ST 15MIN ATMOS ABS,19.73
6303,1,Z7608,HYPERBARIC OXY CHMBR EACH SUB 15 MIN,19.73,19.73,NaN,NaN,9.0,0.0,0.0,0.0,0.0,Y,HYPERBARIC OXY CHMBR EACH SUB 15 MIN,19.73
6304,1,Z9726,INITIAL INFANT HEAR-SCREEN-OUTPATIENT,30.00,30.00,NaN,NaN,9.0,0.0,0.0,0.0,0.0,N,INITIAL INFANT HEAR-SCREEN-OUTPATIENT,30.00
6305,1,Z9727,INFANT HEARING RESCREEN-OUTPATIENT,30.00,30.00,NaN,NaN,9.0,0.0,0.0,0.0,0.0,N,INFANT HEARING RESCREEN-OUTPATIENT,30.00

In [31]:
display(final_df_a)

,SVC_CD,MODIFIER_1,FEE,AGE_UNIT,FROM_AGE,THROUGH_AGE,PLACE_OF_SERVICE_CODE
0,00102,,108.91,,,,
1,00103,,90.84,,,,
2,00104,,72.55,,,,
3,00120,,90.84,,,,
4,00124,,72.55,,,,
...,...,...,...,...,...,...,...
7316,95930,TC,10.37,,,,
7317,95937,TC,7.99,,,,
7318,95955,TC,79.72,,,,
7319,95957,TC,96.80,,,,
7320,95958,TC,70.93,,,,

In [32]:
final_df_a['SVC_CD'].value_counts()

SVC_CD
73100    2
83002    2
82951    2
82952    2
82960    2
        ..
31536    1
31535    1
31531    1
31530    1
Z9727    1
Name: count, Length: 6005, dtype: int64

In [33]:
df_ac['Proc_Code'].value_counts()

Proc_Code
00102    1
65091    1
64905    1
64902    1
64901    1
        ..
32124    1
32120    1
32110    1
32100    1
Z9727    1
Name: count, Length: 6306, dtype: int64

In [34]:
merged_df['Proc_Code'].value_counts()

Proc_Code
00102    1
65091    1
64905    1
64902    1
64901    1
        ..
32124    1
32120    1
32110    1
32100    1
Z9727    1
Name: count, Length: 6306, dtype: int64