In [11]:
import time
import pandas as pd
import os

#Website To download Medical Rates files
# https://mcweb.apps.prd.cammis.medi-cal.ca.gov/rates?page=1&tab=rates
# Rename downloaded excel file to 'Medi-Cal Rates mm.dd.yyyy' format

# Start the timer
start_time = time.time()

#input file
file_path = "../Monthly_Input_Files/Medi-Cal Rates 03.15.2025.xlsx"
date_part = file_path.split(" ")[-1].split(".")  
split_date = '-'.join(date_part[0:3])
month, day, year = split_date.split('-')
if len(year) == 2:
    year = '20' + year
date = f'{year}-{month}-01'

df = pd.read_excel(file_path, skiprows=1)
df_ac= pd.read_excel("../Augment_Codes/Augment Codes.xlsx", skiprows=1)

# Create a directory named after the date if it doesn't exist
if not os.path.exists(f'../Monthly_Output_Files/{date}'):
    os.makedirs(f'../Monthly_Output_Files/{date}')                   
 
# Define new column names based on the data structure in your file
df.columns = ['Proc_Type', 'Proc_Code', 'Procedure_Description', 'Unit_Value',
              'Basic_Rate', 'Child_Rate', 'ER_Rate', 'Conv_Ind', 'ER_Ind',
              'Cutback_Ind', 'Prof_%', 'Rental_Rate', 'Non_Physn_Med_Prac_Ind']

 
# Define columns for Augment Code based on the data structures
df_ac.columns = ['Proc_Code','Procedure_Description_for_Augmentation', 'Basic_rate', 'Proc_Type']

# Remove the $ sign and convert the column to numeric, coerce errors to NaN
df['Basic_Rate'] = pd.to_numeric(df['Basic_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Child_Rate'] = pd.to_numeric(df['Child_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['ER_Rate'] = pd.to_numeric(df['ER_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Rental_Rate'] = pd.to_numeric(df['Rental_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Prof_%'] = pd.to_numeric(df['Prof_%'], errors='coerce').round(2)

def Purchase_Calculation(df,proc_type):
    filtered_df_1 = df.copy()
    filtered_df_1 = filtered_df_1[filtered_df_1['Basic_Rate'] > 0.01]
    filtered_df_1['FEE'] = filtered_df_1['Basic_Rate'].round(2)
    filtered_df_1['MODIFIER_1']='NU'
    filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    filtered_df_1['AGE_UNIT']=''
    filtered_df_1['FROM_AGE']=''
    filtered_df_1['THROUGH_AGE']=''
    filtered_df_1['PLACE_OF_SERVICE_CODE']=''
    
    final_df_a = filtered_df_1[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
    return final_df_a

def Rental_Calculation(df,proc_type):
    filtered_df_1 = df.copy()

    filtered_df_1['FEE']=filtered_df_1['Rental_Rate'].round(2)
    filtered_df_1['MODIFIER_1']='RR'
    filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    filtered_df_1['AGE_UNIT']=''
    filtered_df_1['FROM_AGE']=''
    filtered_df_1['THROUGH_AGE']=''
    filtered_df_1['PLACE_OF_SERVICE_CODE']=''
    final_df_a = filtered_df_1[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
    return final_df_a

def Basic_Rate_Calculation(df,proc_type):
    filtered_df_1 = df[(df['Basic_Rate'] > 0)].copy()
    filtered_df_2 = df[(df['Basic_Rate'] > 0) & (df['Prof_%'] > 0)].copy()
    filtered_df_3 = df[(df['Basic_Rate'] > 0) & (df['Prof_%'] !=0) & (1- df['Prof_%'] > 0)].copy()
    
    filtered_df_1['FEE']=filtered_df_1['Basic_Rate'].round(2)
    filtered_df_1['MODIFIER_1']=''
    filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    # Create a professional rate DataFrame
    prof_df = filtered_df_2.copy()
    prof_df['FEE'] = (prof_df['Basic_Rate'] * prof_df['Prof_%']).round(2)
    prof_df['MODIFIER_1'] = '26'
    prof_df['SVC_CD']=prof_df['Proc_Code']
 
    # Create a technical rate DataFrame
    tech_df = filtered_df_3.copy()
    tech_df['FEE'] = (tech_df['Basic_Rate'] * (1 - tech_df['Prof_%'])).round(2)
    tech_df['MODIFIER_1'] = 'TC'
    tech_df['SVC_CD']=tech_df['Proc_Code']
 
    # Append the technical DataFrame to the professional DataFrame
    result_df = pd.concat([filtered_df_1,prof_df, tech_df], ignore_index=True)
    result_df['AGE_UNIT']=''
    result_df['FROM_AGE']=''
    result_df['THROUGH_AGE']=''
    result_df['PLACE_OF_SERVICE_CODE']=''
    final_df_a = result_df[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
    
    return final_df_a

def Child_Rate_Calculation(df,proc_type):
    # Filter DataFrame for rows where both Prof_% and Basic_Rate are greater than 0
    filtered_df_1 = df[(df['Proc_Type']==proc_type) & (df['Child_Rate'] > 0)].copy()
    filtered_df_2 = df[(df['Proc_Type']==proc_type) & (df['Child_Rate'] > 0) & (df['Prof_%'] > 0)].copy()
    filtered_df_3 = df[(df['Proc_Type']==proc_type) & (df['Child_Rate'] > 0) & (df['Prof_%'] !=0) & (1- df['Prof_%'] > 0)].copy()
    result_df=pd.DataFrame()
    if len(filtered_df_1)>0:
        filtered_df_1['FEE']=filtered_df_1['Child_Rate'].round(2)
        filtered_df_1['MODIFIER_1']=''
        filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    # Create a professional rate DataFrame
        prof_df = filtered_df_2.copy()
        prof_df['FEE'] = (prof_df['Child_Rate'] * prof_df['Prof_%']).round(2)
        prof_df['MODIFIER_1'] = '26'
        prof_df['SVC_CD']=prof_df['Proc_Code']
 
    # Create a technical rate DataFrame
        tech_df = filtered_df_3.copy()
        tech_df['FEE'] = (tech_df['Child_Rate'] * (1 - tech_df['Prof_%'])).round(2)
        tech_df['MODIFIER_1'] = 'TC'
        tech_df['SVC_CD']=tech_df['Proc_Code']
 
    # Append the technical DataFrame to the professional DataFrame
        result_df = pd.concat([filtered_df_1,prof_df, tech_df], ignore_index=True)
        result_df['AGE_UNIT']='3'
        result_df['FROM_AGE']='0'
        result_df['THROUGH_AGE']='18'
        result_df['PLACE_OF_SERVICE_CODE']=''
        result_df = result_df[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
    return result_df

def ER_Rate_Calculation(df,proc_type):
    # Filter DataFrame for rows where both Prof_% and Basic_Rate are greater than 0
    filtered_df_1 = df[(df['Proc_Type']==proc_type) & (df['ER_Rate'] > 0) & (df['ER_Ind']>0)].copy()
    filtered_df_2 = df[(df['Proc_Type']==proc_type) & (df['ER_Rate'] > 0) & (df['Prof_%'] > 0) & (df['ER_Ind']>0)].copy()
    filtered_df_3 = df[(df['Proc_Type']==proc_type) & (df['ER_Rate'] > 0) & (df['Prof_%'] !=0) & (1- df['Prof_%'] > 0) & (df['ER_Ind']>0)].copy()
    
    filtered_df_1['FEE']=filtered_df_1['ER_Rate'].round(2)
    filtered_df_1['MODIFIER_1']=''
    filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    # Create a professional rate DataFrame
    prof_df = filtered_df_2.copy()
    prof_df['FEE'] = (prof_df['ER_Rate'] * prof_df['Prof_%']).round(2)
    prof_df['MODIFIER_1'] = '26'
    prof_df['SVC_CD']=prof_df['Proc_Code']
 
    # Create a technical rate DataFrame
    tech_df = filtered_df_3.copy()
    tech_df['FEE'] = (tech_df['ER_Rate'] * (1 - tech_df['Prof_%'])).round(2)
    tech_df['MODIFIER_1'] = 'TC'
    tech_df['SVC_CD']=tech_df['Proc_Code']
 
    # Append the technical DataFrame to the professional DataFrame
    result_df = pd.concat([filtered_df_1,prof_df, tech_df], ignore_index=True)
    result_df['AGE_UNIT']=''
    result_df['FROM_AGE']=''
    result_df['THROUGH_AGE']=''
    result_df['PLACE_OF_SERVICE_CODE']='23'
    return result_df[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]

def anes_calculation(df,proc_type):
    # Filter DataFrame for rows where both Prof_% and Basic_Rate are greater than 0
    filtered_df_1 = df.copy()
    
    filtered_df_1['CPT Code']=filtered_df_1['Proc_Code']
    filtered_df_1['CPT Descriptor']=filtered_df_1['Procedure_Description']
    filtered_df_1['Base Unit Value']=filtered_df_1['Unit_Value']
    
    filtered_df_1['AGE_UNIT']=''
    filtered_df_1['FROM_AGE']=''
    filtered_df_1['THROUGH_AGE']=''
    filtered_df_1['PLACE_OF_SERVICE_CODE']=''
    final_df_a = filtered_df_1[['CPT Code', 'CPT Descriptor', 'Base Unit Value']]
    
    return final_df_a
# Create a dictionary to hold dataframes for each a_type
df_dict = {}

# Get unique Proc_Types
Proc_Types = df['Proc_Type'].unique()

# Create a dataframe for each Proc_Types and store it in the dictionary
for Proc_Type in Proc_Types:
    df_dict[Proc_Type] = df[df['Proc_Type'] == Proc_Type]

# Initialize a new dictionary to hold the filtered dataframes
filtered_df_dict = {}

# Augment Codes File Processing
merged_df = pd.merge(df, df_ac, how='right', on=['Proc_Code', 'Proc_Type'])
merged_df = merged_df[merged_df['Proc_Type']!= 'J']
#display(merged_df)
df_augment = merged_df
filtered_aug = df_augment[(df_augment['Basic_Rate'] > 0)].copy()
filtered_aug_2 = df_augment[(df_augment['Basic_Rate'] > 0) & (df_augment['Prof_%'] !=0) & (1- df_augment['Prof_%'] > 0)].copy()
    
filtered_aug['FEE']=(filtered_aug['Basic_Rate']*1.4344).round(2)
filtered_aug['MODIFIER_1']=''
filtered_aug['SVC_CD']=filtered_aug['Proc_Code']
    
# Create a technical rate DataFrame for augment codes
tech_df = filtered_aug_2.copy()
tech_df['FEE'] = (tech_df['Basic_Rate'] * (1 - tech_df['Prof_%']) * 1.4344).round(2)
tech_df['MODIFIER_1'] = 'TC'
tech_df['SVC_CD']=tech_df['Proc_Code']
 
# Append the technical DataFrame to the professional DataFrame for augment codes
result_df = pd.concat([filtered_aug, tech_df], ignore_index=True)
result_df['AGE_UNIT']=''
result_df['FROM_AGE']=''
result_df['THROUGH_AGE']=''
result_df['PLACE_OF_SERVICE_CODE']=''
final_df_a = result_df[['SVC_CD', 'MODIFIER_1', 'FEE']]
final_df_a.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Augment.{date}.txt', sep='|', index=False)



# Filter the dataframe for Proc_Type 'I' and Proc_Code starting with 'C','J','S'
if 'I' in df_dict and df_dict['I']['Proc_Code'].str.startswith(('C','J','S','P9','Q')).any():
        filtered_df_dict = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('C','J','S','P9','Q'))].copy()
        filtered_df_dict['Basic_Rate'] = filtered_df_dict['Basic_Rate'] - 4.46
        filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
        Basic_df=Basic_Rate_Calculation(filtered_df_dict,'I')
        Child_df=Child_Rate_Calculation(filtered_df_dict,'I')
        ER_df =ER_Rate_Calculation(filtered_df_dict,'I')
        final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
        # Save the DataFrame to a csv file in the specified directory
        final_df.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Injection.{date}.txt', sep='|', index=False)
#       final_df.to_csv(f'Mcal_Injection.{date}.txt', sep='|', index=False)
        
# Filter the dataframe for Proc_Type 'I' and Proc_Code starting with 'A9','P9','Q'

if 'I' in df_dict and  df_dict['I']['Proc_Code'].str.startswith(('A9','C','J','S','P9','Q')).any():
        filtered_df_dict_a = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('A9'))].copy()
        filtered_df_dict_a = filtered_df_dict_a[(filtered_df_dict_a['Basic_Rate'] > 0)]
        filtered_df_dict_b = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('C','J','S','P9','Q'))].copy()
        filtered_df_dict_b = filtered_df_dict_b[(filtered_df_dict_b['Basic_Rate'] < 4.461)]
        filtered_df_dict = pd.concat([filtered_df_dict_a,filtered_df_dict_b], ignore_index=True)
        Basic_df=Basic_Rate_Calculation(filtered_df_dict,'I')
        Child_df=Child_Rate_Calculation(filtered_df_dict,'I')
        ER_df =ER_Rate_Calculation(filtered_df_dict,'I')
        final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
        # Save the DataFrame to a csv file in the specified directory
        final_df.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Injection_Other.{date}.txt', sep='|', index=False)
#        final_df.to_csv(f'Mcal_Injection_Other.{date}.txt', sep='|', index=False)
        
# Filter the dataframe for Proc_Type 'I' and Proc_Code starting with '90'
if 'I' in df_dict and  df_dict['I']['Proc_Code'].str.startswith(('9')).any():
        filtered_df_dict = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('9'))].copy()
        filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
        Basic_df=Basic_Rate_Calculation(filtered_df_dict,'I')
        Child_df=Child_Rate_Calculation(filtered_df_dict,'I')
        ER_df =ER_Rate_Calculation(filtered_df_dict,'I')
        final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
        final_df.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Vaccines.{date}.txt', sep='|', index=False)
#       final_df.to_csv(f'Mcal_Vaccines.{date}.txt', sep='|', index=False)
        
if 'J' in df_dict:
    filtered_df_dict = df_dict['J'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    anes_df=anes_calculation(filtered_df_dict,'J')
    
    final_df = anes_df
    final_df.to_csv(f'../Monthly_Output_Files/{date}/Anesthesia_Base.{date}.txt', sep=',', index=False)
    #final_df.to_csv(f'Anesthesia_Base.{date}.txt', sep=',', index=False)

if 'K' in df_dict:
    filtered_df_dict = df_dict['K'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'K')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'K')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'K')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Surgical.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Surgical.{date}.txt', sep='|', index=False)
    
if 'L' in df_dict:
    filtered_df_dict = df_dict['L'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'L')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'L')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'L')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Radiology.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Radiology.{date}.txt', sep='|', index=False)
    
if 'M' in df_dict:
    filtered_df_dict = df_dict['M'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'M')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'M')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'M')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Path_and_Lab.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Path_and_Lab.{date}.txt', sep='|', index=False)
    
if 'N' or 'F' in df_dict:
    filtered_df_dict_N = df_dict['N'].copy()
    filtered_df_dict_F = df_dict['F'].copy()
    filtered_df_dict = pd.concat([filtered_df_dict_N,filtered_df_dict_F], ignore_index=True)
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'N')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'N')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'N')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Medicine.{date}.txt', sep='|', index=False)
   # final_df.to_csv(f'MCal_Medicine.{date}.txt', sep='|', index=False)
    
if 'O' in df_dict:
    filtered_df_dict = df_dict['O'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'O')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'O')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'O')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Asst_Surgical.{date}.txt', sep='|', index=False)
#final_df.to_csv(f'MCal_Asst_Surgical.{date}.txt', sep='|', index=False)
    
if 'P' in df_dict:
    filtered_df_dict = df_dict['P'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'P')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'P')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'P')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Podiatrists.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Podiatrists.{date}.txt', sep='|', index=False)
    
if 'Q' in df_dict:
    filtered_df_dict = df_dict['Q'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'Q')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'Q')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'Q')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Behavioral_Health.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Behavioral_Health.{date}.txt', sep='|', index=False)
    
if 'T' in df_dict:
    filtered_df_dict = df_dict['T'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'T')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'T')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'T')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_EPSDT.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_EPSDT.{date}.txt', sep='|', index=False)

if 'X' in df_dict:
    filtered_df_dict = df_dict['X'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'X')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'X')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'X')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_TRI.{date}.txt', sep='|', index=False)

if '3' in df_dict:
    filtered_df_dict = df_dict['3'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'3')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'3')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'3')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Vision.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Vision.{date}.txt', sep='|', index=False)
    
if '1' in df_dict:
    filtered_df_dict_1 = df_dict['1'][(~df_dict['1']['Proc_Code'].str.startswith('A0')) & (df_dict['1']['Rental_Rate'] == 0)].copy()
    filtered_df_dict_1 = filtered_df_dict_1[(filtered_df_dict_1['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict_1,'1')
    Child_df=Child_Rate_Calculation(filtered_df_dict_1,'1')
    ER_df =ER_Rate_Calculation(filtered_df_dict_1,'1')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Allied.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'Mcal_Allied.{date}.txt', sep='|', index=False)

    filtered_df_dict_2 = df_dict['1'][(~df_dict['1']['Proc_Code'].str.startswith('A0')) & (df_dict['1']['Rental_Rate'] > 0)].copy()
    Purchase_df = Purchase_Calculation(filtered_df_dict_2,'1')
    Rental_df = Rental_Calculation(filtered_df_dict_2,'1')
    final_df_2 = pd.concat([Purchase_df,Rental_df], ignore_index=True)
    final_df_2.to_csv(f'../Monthly_Output_Files/{date}/Mcal_DME.{date}.txt', sep='|', index=False)
    #final_df_2.to_csv(f'Mcal_DME.{date}.txt', sep='|', index=False) 
print("code executed succesfully")

# End the timer
end_time = time.time()

# Calculate the time taken
time_taken = end_time - start_time

# Print the time taken
print("Time taken to execute the code is:", time_taken, "seconds")

code executed succesfully
Time taken to execute the code is: 4.03082013130188 seconds

In [1]:
#PADS Code
import pandas as pd
#input file
file_path1 = "../Monthly_Input_Files/pads1.xlsx"
df = pd.read_excel(file_path1, skiprows=0)
df.columns = ['Proc_Code', 'Procedure_Code_Description', 'Procedure_Type', 'Conversion_Indicator',
              'Published_Rate', 'Admin_Fee', 'Subsequent_Units_Fee']
df=df[df['Procedure_Type'] == 'I']
df['Admin_Fee'] = pd.to_numeric(df['Admin_Fee'].astype(str).str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
filtered_df_w_Admin_Fee = df.copy()
filtered_df_w_Admin_Fee = filtered_df_w_Admin_Fee[filtered_df_w_Admin_Fee['Admin_Fee'] == 4.46]

filtered_df_wo_Admin_Fee = df.copy()
filtered_df_wo_Admin_Fee = filtered_df_wo_Admin_Fee[filtered_df_wo_Admin_Fee['Admin_Fee'] != 4.46]


#input file INJ
file_path_Inj = "../Monthly_Output_Files/2025-01-01/Mcal_Injection.2025-01-01.txt"
df_Inj = pd.read_csv(file_path_Inj, sep='|', skiprows=0)
df_Inj

#input file INJ_Other
file_path_Inj_Other = "../Monthly_Output_Files/2025-01-01/Mcal_Injection_Other.2025-01-01.txt"
df_Inj_Other = pd.read_csv(file_path_Inj_Other, sep='|', skiprows=0)
df_Inj_Other

,SVC_CD,MODIFIER_1,FEE,AGE_UNIT,FROM_AGE,THROUGH_AGE,PLACE_OF_SERVICE_CODE
0,A9513,NaN,279.48,NaN,NaN,NaN,NaN
1,A9542,NaN,3490.46,NaN,NaN,NaN,NaN
2,A9543,NaN,61774.82,NaN,NaN,NaN,NaN
3,A9590,NaN,324.85,NaN,NaN,NaN,NaN
4,A9592,NaN,929.46,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
123,J9297,NaN,1.12,NaN,NaN,NaN,NaN
124,J9351,NaN,0.94,NaN,NaN,NaN,NaN
125,J9360,NaN,3.88,NaN,NaN,NaN,NaN
126,Q0138,NaN,0.33,NaN,NaN,NaN,NaN
127,Q0139,NaN,0.33,NaN,NaN,NaN,NaN

In [2]:
df.columns = ['Proc_Code', 'Procedure_Code_Description', 'Procedure_Type', 'Conversion_Indicator',
              'Published_Rate', 'Admin_Fee', 'Subsequent_Units_Fee']
df

,Proc_Code,Procedure_Code_Description,Procedure_Type,Conversion_Indicator,Published_Rate,Admin_Fee,Subsequent_Units_Fee
0,90371,"HEPATITIS B IG (HBIG), HUMAN, IM, 1 ML",I,30,144.39,4.46,139.93
1,90375,"RABIES IG (RIG), HUMAN, IM OR SC, 1 ML",I,30,292.17,4.46,287.71
2,90377,"RABIES IG (RIG-HT S/D), IM OR SC, 150 IU",I,30,269.97,4.46,265.51
3,90378,"INJ, RSV, MAB, RECOMBINANT, IM, 50 MG",I,30,1774.27,4.46,1769.81
5,90632,"HEPATITIS A VACCINE, ADULT, IM, 1 ML",I,30,74.94,4.46,70.48
...,...,...,...,...,...,...,...
610,S0132,"INJ, GANIRELIX ACETATE, 250 MCG",I,30,77.38,4.46,72.92
614,S5552,"INSULIN, NPH OR LENTE, 5 UNITS",I,30,4.78,4.46,0.32
615,S5566,"INSULIN, CARTRIDGE, 300 UNITS",I,30,50.49,4.46,46.03
616,S5571,"INSULIN, DISPOSABLE PEN, 3 ML SIZE",I,30,66.14,4.46,61.68
622,U8-J3490,"INJ, MEDROXYPROGESTERONE ACET, 150 MG/ML",I,30,33.32,4.46,28.86

In [3]:
df=df[df['Procedure_Type'] == 'I']
df

,Proc_Code,Procedure_Code_Description,Procedure_Type,Conversion_Indicator,Published_Rate,Admin_Fee,Subsequent_Units_Fee
0,90371,"HEPATITIS B IG (HBIG), HUMAN, IM, 1 ML",I,30,144.39,4.46,139.93
1,90375,"RABIES IG (RIG), HUMAN, IM OR SC, 1 ML",I,30,292.17,4.46,287.71
2,90377,"RABIES IG (RIG-HT S/D), IM OR SC, 150 IU",I,30,269.97,4.46,265.51
3,90378,"INJ, RSV, MAB, RECOMBINANT, IM, 50 MG",I,30,1774.27,4.46,1769.81
5,90632,"HEPATITIS A VACCINE, ADULT, IM, 1 ML",I,30,74.94,4.46,70.48
...,...,...,...,...,...,...,...
610,S0132,"INJ, GANIRELIX ACETATE, 250 MCG",I,30,77.38,4.46,72.92
614,S5552,"INSULIN, NPH OR LENTE, 5 UNITS",I,30,4.78,4.46,0.32
615,S5566,"INSULIN, CARTRIDGE, 300 UNITS",I,30,50.49,4.46,46.03
616,S5571,"INSULIN, DISPOSABLE PEN, 3 ML SIZE",I,30,66.14,4.46,61.68
622,U8-J3490,"INJ, MEDROXYPROGESTERONE ACET, 150 MG/ML",I,30,33.32,4.46,28.86

In [4]:
df['Admin_Fee'] = pd.to_numeric(df['Admin_Fee'].astype(str).str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
filtered_df_1 = df.copy()
filtered_df_1 = filtered_df_1[filtered_df_1['Admin_Fee'] == 4.46]
filtered_df_1

,Proc_Code,Procedure_Code_Description,Procedure_Type,Conversion_Indicator,Published_Rate,Admin_Fee,Subsequent_Units_Fee
0,90371,"HEPATITIS B IG (HBIG), HUMAN, IM, 1 ML",I,30,144.39,4.46,139.93
1,90375,"RABIES IG (RIG), HUMAN, IM OR SC, 1 ML",I,30,292.17,4.46,287.71
2,90377,"RABIES IG (RIG-HT S/D), IM OR SC, 150 IU",I,30,269.97,4.46,265.51
3,90378,"INJ, RSV, MAB, RECOMBINANT, IM, 50 MG",I,30,1774.27,4.46,1769.81
5,90632,"HEPATITIS A VACCINE, ADULT, IM, 1 ML",I,30,74.94,4.46,70.48
...,...,...,...,...,...,...,...
610,S0132,"INJ, GANIRELIX ACETATE, 250 MCG",I,30,77.38,4.46,72.92
614,S5552,"INSULIN, NPH OR LENTE, 5 UNITS",I,30,4.78,4.46,0.32
615,S5566,"INSULIN, CARTRIDGE, 300 UNITS",I,30,50.49,4.46,46.03
616,S5571,"INSULIN, DISPOSABLE PEN, 3 ML SIZE",I,30,66.14,4.46,61.68
622,U8-J3490,"INJ, MEDROXYPROGESTERONE ACET, 150 MG/ML",I,30,33.32,4.46,28.86

In [5]:
filtered_df_2 = df.copy()
filtered_df_2 = filtered_df_2[filtered_df_2['Admin_Fee'] != 4.46]
filtered_df_2

,Proc_Code,Procedure_Code_Description,Procedure_Type,Conversion_Indicator,Published_Rate,Admin_Fee,Subsequent_Units_Fee
25,A9543,"YTTRIUM Y-90 IBRITUMOM, TX, UP TO 40 MCI",I,9,64858.88,NaN,64858.88
27,C9170,"INJ, TARLATAMAB-DLLE, 1 MG",I,9,1500.00,NaN,1500.00
28,C9171,"INJ, PEGULICIANINE, 1 MG",I,9,35.38,NaN,35.38
29,C9254,"INJ, LACOSAMIDE, 1 MG",I,9,0.42,NaN,0.42
31,J0121,"INJ, OMADACYCLINE, 1 MG",I,9,3.80,NaN,3.80
...,...,...,...,...,...,...,...
595,Q5126,"INJ, BEVACIZUMAB-MALY, BIOSIMILAR, (ALYMSYS), ...",I,9,56.86,NaN,56.86
597,Q5128,"INJ, RANIBIZUMAB-EQRN (CIMERLI), BIOSIMILAR, 0...",I,9,201.01,NaN,201.01
598,Q5129,"INJ, BEVACIZUMAB-ADCD (VEGZELMA), BIOSIMILAR, ...",I,9,56.82,NaN,56.82
601,Q5133,"INJ, TOCILIZUMAB-BAVI, TOFIDENCE, 1 MG",I,9,5.55,NaN,5.55
606,S0039,"INJ, SULFAMETHOX/TRIMETHOPRIM, 10 ML",I,9,12.09,NaN,12.09

In [6]:
#input file INJ
file_path_Inj = "../Monthly_Output_Files/2025-01-01/Mcal_Injection.2025-01-01.txt"
df_Inj = pd.read_csv(file_path_Inj, sep='|', skiprows=0)
df_Inj

#input file INJ_Other
file_path_Inj_Other = "../Monthly_Output_Files/2025-01-01/Mcal_Injection_Other.2025-01-01.txt"
df_Inj_Other = pd.read_csv(file_path_Inj_Other, sep='|', skiprows=0)
df_Inj_Other

,SVC_CD,MODIFIER_1,FEE,AGE_UNIT,FROM_AGE,THROUGH_AGE,PLACE_OF_SERVICE_CODE
0,A9513,NaN,279.48,NaN,NaN,NaN,NaN
1,A9542,NaN,3490.46,NaN,NaN,NaN,NaN
2,A9543,NaN,61774.82,NaN,NaN,NaN,NaN
3,A9590,NaN,324.85,NaN,NaN,NaN,NaN
4,A9592,NaN,929.46,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
123,J9297,NaN,1.12,NaN,NaN,NaN,NaN
124,J9351,NaN,0.94,NaN,NaN,NaN,NaN
125,J9360,NaN,3.88,NaN,NaN,NaN,NaN
126,Q0138,NaN,0.33,NaN,NaN,NaN,NaN
127,Q0139,NaN,0.33,NaN,NaN,NaN,NaN

In [7]:
#input file INJ_Other
file_path_Inj_Other = "../Monthly_Output_Files/2025-01-01/Mcal_Injection_Other.2025-01-01.txt"
df_Inj_Other = pd.read_csv(file_path_Inj_Other, sep='|', skiprows=0)
df_Inj_Other

,SVC_CD,MODIFIER_1,FEE,AGE_UNIT,FROM_AGE,THROUGH_AGE,PLACE_OF_SERVICE_CODE
0,A9513,NaN,279.48,NaN,NaN,NaN,NaN
1,A9542,NaN,3490.46,NaN,NaN,NaN,NaN
2,A9543,NaN,61774.82,NaN,NaN,NaN,NaN
3,A9590,NaN,324.85,NaN,NaN,NaN,NaN
4,A9592,NaN,929.46,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
123,J9297,NaN,1.12,NaN,NaN,NaN,NaN
124,J9351,NaN,0.94,NaN,NaN,NaN,NaN
125,J9360,NaN,3.88,NaN,NaN,NaN,NaN
126,Q0138,NaN,0.33,NaN,NaN,NaN,NaN
127,Q0139,NaN,0.33,NaN,NaN,NaN,NaN

In [31]:
import pandas as pd

# Load PADS sheet and Mcal Injection files
file_path1 = "../Monthly_Input_Files/pads1.xlsx"
df = pd.read_excel(file_path1, skiprows=0)
df.columns = ['Proc_Code', 'Procedure_Code_Description', 'Procedure_Type', 'Conversion_Indicator',
              'Published_Rate', 'Admin_Fee', 'Subsequent_Units_Fee']
df = df[df['Procedure_Type'] == 'I']
df['Admin_Fee'] = pd.to_numeric(df['Admin_Fee'].astype(str).str.replace('[\$,]', '', regex=True), errors='coerce').round(2)

# Separate dataframes with Admin Fee 4.46 and without
filtered_df_w_Admin_Fee = df[df['Admin_Fee'] == 4.46]
filtered_df_wo_Admin_Fee = df[df['Admin_Fee'] != 4.46]

# Load the "MCal Injection" file
file_path_Inj = "../Monthly_Output_Files/2025-01-01/Mcal_Injection.2025-01-01.txt"
df_Inj = pd.read_csv(file_path_Inj, sep='|', skiprows=0)
df_Inj.columns = ['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE','PLACE_OF_SERVICE_CODE']

# Load the "MCal Injection Other" file
file_path_Inj_Other = "../Monthly_Output_Files/2025-01-01/Mcal_Injection_Other.2025-01-01.txt"
df_Inj_Other = pd.read_csv(file_path_Inj_Other, sep='|', skiprows=0)
df_Inj_Other.columns = ['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE','PLACE_OF_SERVICE_CODE']
# Extract the codes from filtered_df_wo_Admin_Fee
codes_without_admin_fee = filtered_df_wo_Admin_Fee['Proc_Code'].unique()

# Find rows in df_Inj that don't have an Admin Fee in filtered_df_w_Admin_Fee
df_Inj_to_move = df_Inj[~df_Inj['SVC_CD'].isin(filtered_df_w_Admin_Fee['Proc_Code'])]
df_Inj_to_move
# Now move those rows to df_Inj_Other
df_Inj_Other = pd.concat([df_Inj_Other, df_Inj_to_move])

# Optionally, you can now save these DataFrames if needed
# df_Inj_Other.to_csv("updated_Mcal_Injection_Other.txt", sep='|', index=False)

df_Inj_Other  # This will now contain the moved rows

,SVC_CD,MODIFIER_1,FEE,AGE_UNIT,FROM_AGE,THROUGH_AGE,PLACE_OF_SERVICE_CODE
0,A9513,NaN,279.48,NaN,NaN,NaN,NaN
1,A9542,NaN,3490.46,NaN,NaN,NaN,NaN
2,A9543,NaN,61774.82,NaN,NaN,NaN,NaN
3,A9590,NaN,324.85,NaN,NaN,NaN,NaN
4,A9592,NaN,929.46,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
610,S0145,NaN,1113.42,NaN,NaN,NaN,NaN
611,S0148,NaN,150.43,NaN,NaN,NaN,NaN
612,S5550,NaN,0.69,NaN,NaN,NaN,NaN
613,S5551,NaN,0.79,NaN,NaN,NaN,NaN
615,S5553,NaN,0.83,NaN,NaN,NaN,NaN

In [32]:
df_Inj_to_move

,SVC_CD,MODIFIER_1,FEE,AGE_UNIT,FROM_AGE,THROUGH_AGE,PLACE_OF_SERVICE_CODE
0,C9047,NaN,749.27,NaN,NaN,NaN,NaN
1,C9101,NaN,1.13,NaN,NaN,NaN,NaN
2,C9144,NaN,0.48,NaN,NaN,NaN,NaN
3,C9145,NaN,1.81,NaN,NaN,NaN,NaN
4,C9293,NaN,407.28,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
610,S0145,NaN,1113.42,NaN,NaN,NaN,NaN
611,S0148,NaN,150.43,NaN,NaN,NaN,NaN
612,S5550,NaN,0.69,NaN,NaN,NaN,NaN
613,S5551,NaN,0.79,NaN,NaN,NaN,NaN
615,S5553,NaN,0.83,NaN,NaN,NaN,NaN

In [12]:
import pandas as pd
import os
# Load PADS sheet and Mcal Injection files
file_path1 = "../Monthly_Input_Files/pads1.xlsx"
df = pd.read_excel(file_path1, skiprows=0)
df.columns = ['Proc_Code', 'Procedure_Code_Description', 'Procedure_Type', 'Conversion_Indicator',
              'Published_Rate', 'Admin_Fee', 'Subsequent_Units_Fee']
df = df[df['Procedure_Type'] == 'I']
df['Admin_Fee'] = pd.to_numeric(df['Admin_Fee'].astype(str).str.replace('[\$,]', '', regex=True), errors='coerce').round(2)

# Load the "MCal Injection" file
file_path_Inj = "../Monthly_Output_Files/2025-03-01/Mcal_Injection.2025-03-01.txt"
df_Inj = pd.read_csv(file_path_Inj, sep='|', skiprows=0)
df_Inj.columns = ['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']

# Load the "MCal Injection Other" file
file_path_Inj_Other = "../Monthly_Output_Files/2025-03-01/Mcal_Injection_Other.2025-03-01.txt"
df_Inj_Other = pd.read_csv(file_path_Inj_Other, sep='|', skiprows=0)
df_Inj_Other.columns = ['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']


# Create a directory named after the date if it doesn't exist
if not os.path.exists(f'../Monthly_Output_Files/2025-03-01/pads'):
    os.makedirs(f'../Monthly_Output_Files/2025-03-01/pads')   

# Separate dataframes with Admin Fee 4.46 and without
filtered_df_w_Admin_Fee = df[df['Admin_Fee'] == 4.46]
filtered_df_wo_Admin_Fee = df[df['Admin_Fee'] != 4.46]



# Display df_Inj before moving
print("df_Inj before moving rows:")
print(df_Inj)

# Extract the codes from filtered_df_wo_Admin_Fee
codes_without_admin_fee = filtered_df_wo_Admin_Fee['Proc_Code'].unique()

# Find rows in df_Inj that don't have an Admin Fee in filtered_df_w_Admin_Fee
df_Inj_to_move = df_Inj[~df_Inj['SVC_CD'].isin(filtered_df_w_Admin_Fee['Proc_Code'])]

# Display the rows that will be moved
print("\ndf_Inj rows to be moved to df_Inj_Other:")
print(df_Inj_to_move)

# Move those rows to df_Inj_Other
df_Inj_Other = pd.concat([df_Inj_Other, df_Inj_to_move])

# Remove the moved rows from df_Inj
df_Inj = df_Inj[~df_Inj['SVC_CD'].isin(df_Inj_to_move['SVC_CD'])]

# Display df_Inj after moving
print("\ndf_Inj after moving rows:")
print(df_Inj)

# Optionally, save the updated df_Inj_Other to a new file
# df_Inj_Other.to_csv("updated_Mcal_Injection_Other.txt", sep='|', index=False)
df_Inj.to_csv(f'../Monthly_Output_Files/2025-03-01/pads/Mcal_Injection.2025-03-01.txt', sep='|', index=False)
df_Inj_Other.to_csv(f'../Monthly_Output_Files/2025-03-01/pads/Mcal_Injection_Other.2025-03-01.txt', sep='|', index=False)

df_Inj before moving rows:
    SVC_CD  MODIFIER_1     FEE  AGE_UNIT  FROM_AGE  THROUGH_AGE  \
0    C9047         NaN  749.27       NaN       NaN          NaN
1    C9101         NaN    1.13       NaN       NaN          NaN
2    C9144         NaN    0.48       NaN       NaN          NaN
3    C9145         NaN    1.81       NaN       NaN          NaN
4    C9293         NaN  407.28       NaN       NaN          NaN
..     ...         ...     ...       ...       ...          ...
613  S5551         NaN    0.79       NaN       NaN          NaN
614  S5552         NaN    0.32       NaN       NaN          NaN
615  S5553         NaN    0.83       NaN       NaN          NaN
616  S5566         NaN   46.03       NaN       NaN          NaN
617  S5571         NaN   61.68       NaN       NaN          NaN

     PLACE_OF_SERVICE_CODE
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
..                     ...
613                    NaN
614                    NaN
615                    NaN
616                    NaN
617                    NaN

[618 rows x 7 columns]

df_Inj rows to be moved to df_Inj_Other:
    SVC_CD  MODIFIER_1      FEE  AGE_UNIT  FROM_AGE  THROUGH_AGE  \
0    C9047         NaN   749.27       NaN       NaN          NaN
1    C9101         NaN     1.13       NaN       NaN          NaN
2    C9144         NaN     0.48       NaN       NaN          NaN
3    C9145         NaN     1.81       NaN       NaN          NaN
4    C9293         NaN   407.28       NaN       NaN          NaN
..     ...         ...      ...       ...       ...          ...
610  S0145         NaN  1113.42       NaN       NaN          NaN
611  S0148         NaN   150.43       NaN       NaN          NaN
612  S5550         NaN     0.69       NaN       NaN          NaN
613  S5551         NaN     0.79       NaN       NaN          NaN
615  S5553         NaN     0.83       NaN       NaN          NaN

     PLACE_OF_SERVICE_CODE
0                      NaN
1                      NaN
2                      NaN
3                      NaN
4                      NaN
..                     ...
610                    NaN
611                    NaN
612                    NaN
613                    NaN
615                    NaN

[406 rows x 7 columns]

df_Inj after moving rows:
    SVC_CD  MODIFIER_1     FEE  AGE_UNIT  FROM_AGE  THROUGH_AGE  \
9    J0129         NaN   43.44       NaN       NaN          NaN
10   J0171         NaN    0.83       NaN       NaN          NaN
17   J0185         NaN    1.77       NaN       NaN          NaN
19   J0206         NaN    5.00       NaN       NaN          NaN
30   J0223         NaN  112.14       NaN       NaN          NaN
..     ...         ...     ...       ...       ...          ...
608  S0080         NaN  138.99       NaN       NaN          NaN
609  S0132         NaN   72.92       NaN       NaN          NaN
614  S5552         NaN    0.32       NaN       NaN          NaN
616  S5566         NaN   46.03       NaN       NaN          NaN
617  S5571         NaN   61.68       NaN       NaN          NaN

     PLACE_OF_SERVICE_CODE
9                      NaN
10                     NaN
17                     NaN
19                     NaN
30                     NaN
..                     ...
608                    NaN
609                    NaN
614                    NaN
616                    NaN
617                    NaN

[212 rows x 7 columns]

In [ ]:
###########
## NEW FILE ##

In [3]:
import time
import pandas as pd
import os
 
#Website To download Medical Rates files
# https://mcweb.apps.prd.cammis.medi-cal.ca.gov/rates?page=1&tab=rates
# Rename downloaded excel file to 'Medi-Cal Rates mm.dd.yyyy' format
 
# Start the timer
start_time = time.time()
 
#input file
file_path = "../Monthly_Input_Files/Medi-Cal Rates 01.15.2025.xlsx"
date_part = file_path.split(" ")[-1].split(".")  
split_date = '-'.join(date_part[0:3])
month, day, year = split_date.split('-')
if len(year) == 2:
    year = '20' + year
date = f'{year}-{month}-01'
 
df = pd.read_excel(file_path, skiprows=1)
df_ac= pd.read_excel("../Augment_Codes/Augment Codes.xlsx", skiprows=1)
 
# Create a directory named after the date if it doesn't exist
if not os.path.exists(f'../Monthly_Output_Files/{date}'):
    os.makedirs(f'../Monthly_Output_Files/{date}')                  
 
# Define new column names based on the data structure in your file
df.columns = ['Proc_Type', 'Proc_Code', 'Procedure_Description', 'Unit_Value',
              'Basic_Rate', 'Child_Rate', 'ER_Rate', 'Conv_Ind', 'ER_Ind',
              'Cutback_Ind', 'Prof_%', 'Rental_Rate', 'Non_Physn_Med_Prac_Ind']
 
 
# Define columns for Augment Code based on the data structures
df_ac.columns = ['Proc_Code','Procedure_Description_for_Augmentation', 'Basic_rate', 'Proc_Type']
 
# Remove the $ sign and convert the column to numeric, coerce errors to NaN
df['Basic_Rate'] = pd.to_numeric(df['Basic_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Child_Rate'] = pd.to_numeric(df['Child_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['ER_Rate'] = pd.to_numeric(df['ER_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Rental_Rate'] = pd.to_numeric(df['Rental_Rate'].str.replace('[\$,]', '', regex=True), errors='coerce').round(2)
df['Prof_%'] = pd.to_numeric(df['Prof_%'], errors='coerce').round(2)
 
def Purchase_Calculation(df,proc_type):
    filtered_df_1 = df.copy()
    filtered_df_1 = filtered_df_1[filtered_df_1['Basic_Rate'] > 0.01]
    filtered_df_1['FEE'] = filtered_df_1['Basic_Rate'].round(2)
    filtered_df_1['MODIFIER_1']='NU'
    filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    filtered_df_1['AGE_UNIT']=''
    filtered_df_1['FROM_AGE']=''
    filtered_df_1['THROUGH_AGE']=''
    filtered_df_1['PLACE_OF_SERVICE_CODE']=''
   
    final_df_a = filtered_df_1[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
    return final_df_a
 
def Rental_Calculation(df,proc_type):
    filtered_df_1 = df.copy()
 
    filtered_df_1['FEE']=filtered_df_1['Rental_Rate'].round(2)
    filtered_df_1['MODIFIER_1']='RR'
    filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    filtered_df_1['AGE_UNIT']=''
    filtered_df_1['FROM_AGE']=''
    filtered_df_1['THROUGH_AGE']=''
    filtered_df_1['PLACE_OF_SERVICE_CODE']=''
    final_df_a = filtered_df_1[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
    return final_df_a
 
def Basic_Rate_Calculation(df,proc_type):
    filtered_df_1 = df[(df['Basic_Rate'] > 0)].copy()
    filtered_df_2 = df[(df['Basic_Rate'] > 0) & (df['Prof_%'] > 0)].copy()
    filtered_df_3 = df[(df['Basic_Rate'] > 0) & (df['Prof_%'] !=0) & (1- df['Prof_%'] > 0)].copy()
   
    filtered_df_1['FEE']=filtered_df_1['Basic_Rate'].round(2)
    filtered_df_1['MODIFIER_1']=''
    filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    # Create a professional rate DataFrame
    prof_df = filtered_df_2.copy()
    prof_df['FEE'] = (prof_df['Basic_Rate'] * prof_df['Prof_%']).round(2)
    prof_df['MODIFIER_1'] = '26'
    prof_df['SVC_CD']=prof_df['Proc_Code']
 
    # Create a technical rate DataFrame
    tech_df = filtered_df_3.copy()
    tech_df['FEE'] = (tech_df['Basic_Rate'] * (1 - tech_df['Prof_%'])).round(2)
    tech_df['MODIFIER_1'] = 'TC'
    tech_df['SVC_CD']=tech_df['Proc_Code']
 
    # Append the technical DataFrame to the professional DataFrame
    result_df = pd.concat([filtered_df_1,prof_df, tech_df], ignore_index=True)
    result_df['AGE_UNIT']=''
    result_df['FROM_AGE']=''
    result_df['THROUGH_AGE']=''
    result_df['PLACE_OF_SERVICE_CODE']=''
    final_df_a = result_df[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
   
    return final_df_a
 
def Child_Rate_Calculation(df,proc_type):
    # Filter DataFrame for rows where both Prof_% and Basic_Rate are greater than 0
    filtered_df_1 = df[(df['Proc_Type']==proc_type) & (df['Child_Rate'] > 0)].copy()
    filtered_df_2 = df[(df['Proc_Type']==proc_type) & (df['Child_Rate'] > 0) & (df['Prof_%'] > 0)].copy()
    filtered_df_3 = df[(df['Proc_Type']==proc_type) & (df['Child_Rate'] > 0) & (df['Prof_%'] !=0) & (1- df['Prof_%'] > 0)].copy()
    result_df=pd.DataFrame()
    if len(filtered_df_1)>0:
        filtered_df_1['FEE']=filtered_df_1['Child_Rate'].round(2)
        filtered_df_1['MODIFIER_1']=''
        filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    # Create a professional rate DataFrame
        prof_df = filtered_df_2.copy()
        prof_df['FEE'] = (prof_df['Child_Rate'] * prof_df['Prof_%']).round(2)
        prof_df['MODIFIER_1'] = '26'
        prof_df['SVC_CD']=prof_df['Proc_Code']
 
    # Create a technical rate DataFrame
        tech_df = filtered_df_3.copy()
        tech_df['FEE'] = (tech_df['Child_Rate'] * (1 - tech_df['Prof_%'])).round(2)
        tech_df['MODIFIER_1'] = 'TC'
        tech_df['SVC_CD']=tech_df['Proc_Code']
 
    # Append the technical DataFrame to the professional DataFrame
        result_df = pd.concat([filtered_df_1,prof_df, tech_df], ignore_index=True)
        result_df['AGE_UNIT']='3'
        result_df['FROM_AGE']='0'
        result_df['THROUGH_AGE']='18'
        result_df['PLACE_OF_SERVICE_CODE']=''
        result_df = result_df[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
    return result_df
 
def ER_Rate_Calculation(df,proc_type):
    # Filter DataFrame for rows where both Prof_% and Basic_Rate are greater than 0
    filtered_df_1 = df[(df['Proc_Type']==proc_type) & (df['ER_Rate'] > 0) & (df['ER_Ind']>0)].copy()
    filtered_df_2 = df[(df['Proc_Type']==proc_type) & (df['ER_Rate'] > 0) & (df['Prof_%'] > 0) & (df['ER_Ind']>0)].copy()
    filtered_df_3 = df[(df['Proc_Type']==proc_type) & (df['ER_Rate'] > 0) & (df['Prof_%'] !=0) & (1- df['Prof_%'] > 0) & (df['ER_Ind']>0)].copy()
   
    filtered_df_1['FEE']=filtered_df_1['ER_Rate'].round(2)
    filtered_df_1['MODIFIER_1']=''
    filtered_df_1['SVC_CD']=filtered_df_1['Proc_Code']
    # Create a professional rate DataFrame
    prof_df = filtered_df_2.copy()
    prof_df['FEE'] = (prof_df['ER_Rate'] * prof_df['Prof_%']).round(2)
    prof_df['MODIFIER_1'] = '26'
    prof_df['SVC_CD']=prof_df['Proc_Code']
 
    # Create a technical rate DataFrame
    tech_df = filtered_df_3.copy()
    tech_df['FEE'] = (tech_df['ER_Rate'] * (1 - tech_df['Prof_%'])).round(2)
    tech_df['MODIFIER_1'] = 'TC'
    tech_df['SVC_CD']=tech_df['Proc_Code']
 
    # Append the technical DataFrame to the professional DataFrame
    result_df = pd.concat([filtered_df_1,prof_df, tech_df], ignore_index=True)
    result_df['AGE_UNIT']=''
    result_df['FROM_AGE']=''
    result_df['THROUGH_AGE']=''
    result_df['PLACE_OF_SERVICE_CODE']='23'
    return result_df[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
 
 
    # Append the technical DataFrame to the professional DataFrame
    result_df = pd.concat([filtered_df_1,prof_df, tech_df], ignore_index=True)
    result_df['AGE_UNIT']=''
    result_df['FROM_AGE']=''
    result_df['THROUGH_AGE']=''
    result_df['PLACE_OF_SERVICE_CODE']='23'
    return result_df[['SVC_CD', 'MODIFIER_1', 'FEE', 'AGE_UNIT', 'FROM_AGE', 'THROUGH_AGE', 'PLACE_OF_SERVICE_CODE']]
 
def anes_calculation(df,proc_type):
    # Filter DataFrame for rows where both Prof_% and Basic_Rate are greater than 0
    filtered_df_1 = df.copy()
   
    filtered_df_1['CPT Code']=filtered_df_1['Proc_Code']
    filtered_df_1['CPT Descriptor']=filtered_df_1['Procedure_Description']
    filtered_df_1['Base Unit Value']=filtered_df_1['Unit_Value']
   
    filtered_df_1['AGE_UNIT']=''
    filtered_df_1['FROM_AGE']=''
    filtered_df_1['THROUGH_AGE']=''
    filtered_df_1['PLACE_OF_SERVICE_CODE']=''
    final_df_a = filtered_df_1[['CPT Code', 'CPT Descriptor', 'Base Unit Value']]
   
    return final_df_a
# Create a dictionary to hold dataframes for each a_type
df_dict = {}
 
# Get unique Proc_Types
Proc_Types = df['Proc_Type'].unique()
 
# Create a dataframe for each Proc_Types and store it in the dictionary
for Proc_Type in Proc_Types:
    df_dict[Proc_Type] = df[df['Proc_Type'] == Proc_Type]
 
# Initialize a new dictionary to hold the filtered dataframes
filtered_df_dict = {}
 
# Augment Codes File Processing
merged_df = pd.merge(df, df_ac, how='right', on=['Proc_Code', 'Proc_Type'])
merged_df = merged_df[merged_df['Proc_Type']!= 'J']
#display(merged_df)
df_augment = merged_df
filtered_aug = df_augment[(df_augment['Basic_Rate'] > 0)].copy()
filtered_aug_2 = df_augment[(df_augment['Basic_Rate'] > 0) & (df_augment['Prof_%'] !=0) & (1- df_augment['Prof_%'] > 0)].copy()
   
filtered_aug['FEE']=(filtered_aug['Basic_Rate']*1.4344).round(2)
filtered_aug['MODIFIER_1']=''
filtered_aug['SVC_CD']=filtered_aug['Proc_Code']
   
# Create a technical rate DataFrame for augment codes
tech_df = filtered_aug_2.copy()
tech_df['FEE'] = (tech_df['Basic_Rate'] * (1 - tech_df['Prof_%']) * 1.4344).round(2)
tech_df['MODIFIER_1'] = 'TC'
tech_df['SVC_CD']=tech_df['Proc_Code']
 
# Append the technical DataFrame to the professional DataFrame for augment codes
result_df = pd.concat([filtered_aug, tech_df], ignore_index=True)
result_df['AGE_UNIT']=''
result_df['FROM_AGE']=''
result_df['THROUGH_AGE']=''
result_df['PLACE_OF_SERVICE_CODE']=''
final_df_a = result_df[['SVC_CD', 'MODIFIER_1', 'FEE']]
final_df_a.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Augment.{date}.txt', sep='|', index=False)
 
 
 
# Filter the dataframe for Proc_Type 'I' and Proc_Code starting with 'C','J','S'
if 'I' in df_dict and df_dict['I']['Proc_Code'].str.startswith(('C', 'J', 'S', 'P9', 'Q')).any():
    filtered_df_dict = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('C', 'J', 'S', 'P9', 'Q'))].copy()
    # Adjusting the Basic Rate condition: Basic Rate - 4.46 > 0 and Conv Ind NOT '009'
    filtered_df_dict['Basic_Rate'] = filtered_df_dict['Basic_Rate'] - 4.46
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0) & (filtered_df_dict['Conv_Ind'] != '009')]
    # Apply Basic Rate Calculation for Prof and Tech
    Basic_df = Basic_Rate_Calculation(filtered_df_dict, 'I')
    # Adjusting the Child Rate condition: Child Rate - 4.46 > 0 and Conv Ind NOT '009'
    filtered_df_dict['Child_Rate'] = filtered_df_dict['Child_Rate'] - 4.46
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Child_Rate'] > 0) & (filtered_df_dict['Conv_Ind'] != '009')]
    # Apply Child Rate Calculation for Prof and Tech
    Child_df = Child_Rate_Calculation(filtered_df_dict, 'I')
    # Adjusting the ER Rate condition: ER Rate - 4.46 > 0 and ER Ind > 0 and Conv Ind NOT '009'
    filtered_df_dict['ER_Rate'] = filtered_df_dict['ER_Rate'] - 4.46
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['ER_Rate'] > 0) & (filtered_df_dict['ER_Ind'] > 0) & (filtered_df_dict['Conv_Ind'] != '009')]
    ER_df = ER_Rate_Calculation(filtered_df_dict, 'I')
    final_df = pd.concat([Basic_df, Child_df, ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Injection.{date}.txt', sep='|', index=False)
    # Or use this line if you're saving without the directory path
    # final_df.to_csv(f'Mcal_Injection.{date}.txt', sep='|', index=False)
 
       
# Filter the dataframe for Proc_Type 'I' and Proc_Code starting with 'A9','P9','Q'
 
if 'I' in df_dict and df_dict['I']['Proc_Code'].str.startswith(('A9', 'C', 'J', 'S', 'P9', 'Q')).any():
    # Filter records based on new conditions
    # For Proc_Code starting with 'A9' (Basic Rate > 0)
    filtered_df_dict_a = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('A9'))].copy()
    filtered_df_dict_a = filtered_df_dict_a[(filtered_df_dict_a['Basic_Rate'] > 0)]
    # For Proc_Code starting with ('C', 'J', 'S', 'P9', 'Q') with additional condition for Basic_Rate or Conv_Ind
    filtered_df_dict_b = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('C', 'J', 'S', 'P9', 'Q'))].copy()
    filtered_df_dict_b = filtered_df_dict_b[(filtered_df_dict_b['Basic_Rate'] - 4.46 <= 0) | (filtered_df_dict_b['Conv_Ind'] == '009')]
    # For Child Rate - applying the same condition as Basic Rate
    filtered_df_dict_c = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('C', 'J', 'S', 'P9', 'Q'))].copy()
    filtered_df_dict_c = filtered_df_dict_c[(filtered_df_dict_c['Child_Rate'] - 4.46 <= 0) | (filtered_df_dict_c['Conv_Ind'] == '009')]
    # For ER Rate - applying the same condition as Basic Rate
    filtered_df_dict_d = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('C', 'J', 'S', 'P9', 'Q'))].copy()
    filtered_df_dict_d = filtered_df_dict_d[(filtered_df_dict_d['ER_Rate'] - 4.46 <= 0) | (filtered_df_dict_d['Conv_Ind'] == '009')]
    # Combine all filtered dataframes (Basic, Child, ER, and the others)
    filtered_df_dict = pd.concat([filtered_df_dict_a, filtered_df_dict_b, filtered_df_dict_c, filtered_df_dict_d], ignore_index=True)
    # Apply the calculations for Basic, Child, and ER Rates
    Basic_df = Basic_Rate_Calculation(filtered_df_dict, 'I')
    Child_df = Child_Rate_Calculation(filtered_df_dict, 'I')
    ER_df = ER_Rate_Calculation(filtered_df_dict, 'I')
    # Combine all dataframes into the final result
    final_df = pd.concat([Basic_df, Child_df, ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Injection_Other.{date}.txt', sep='|', index=False)
 
       
# Filter the dataframe for Proc_Type 'I' and Proc_Code starting with '90'
if 'I' in df_dict and  df_dict['I']['Proc_Code'].str.startswith(('9')).any():
        filtered_df_dict = df_dict['I'][df_dict['I']['Proc_Code'].str.startswith(('9'))].copy()
        filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
        Basic_df=Basic_Rate_Calculation(filtered_df_dict,'I')
        Child_df=Child_Rate_Calculation(filtered_df_dict,'I')
        ER_df =ER_Rate_Calculation(filtered_df_dict,'I')
        final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
        final_df.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Vaccines.{date}.txt', sep='|', index=False)
#       final_df.to_csv(f'Mcal_Vaccines.{date}.txt', sep='|', index=False)
       
if 'J' in df_dict:
    filtered_df_dict = df_dict['J'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    anes_df=anes_calculation(filtered_df_dict,'J')
   
    final_df = anes_df
    final_df.to_csv(f'../Monthly_Output_Files/{date}/Anesthesia_Base.{date}.txt', sep=',', index=False)
    #final_df.to_csv(f'Anesthesia_Base.{date}.txt', sep=',', index=False)
 
if 'K' in df_dict:
    filtered_df_dict = df_dict['K'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'K')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'K')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'K')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Surgical.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Surgical.{date}.txt', sep='|', index=False)
   
if 'L' in df_dict:
    filtered_df_dict = df_dict['L'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'L')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'L')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'L')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Radiology.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Radiology.{date}.txt', sep='|', index=False)
   
if 'M' in df_dict:
    filtered_df_dict = df_dict['M'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'M')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'M')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'M')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Path_and_Lab.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Path_and_Lab.{date}.txt', sep='|', index=False)
   
if 'N' or 'F' in df_dict:
    filtered_df_dict_N = df_dict['N'].copy()
    filtered_df_dict_F = df_dict['F'].copy()
    filtered_df_dict = pd.concat([filtered_df_dict_N,filtered_df_dict_F], ignore_index=True)
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'N')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'N')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'N')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Medicine.{date}.txt', sep='|', index=False)
   # final_df.to_csv(f'MCal_Medicine.{date}.txt', sep='|', index=False)
   
if 'O' in df_dict:
    filtered_df_dict = df_dict['O'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'O')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'O')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'O')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Asst_Surgical.{date}.txt', sep='|', index=False)
#final_df.to_csv(f'MCal_Asst_Surgical.{date}.txt', sep='|', index=False)
   
if 'P' in df_dict:
    filtered_df_dict = df_dict['P'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'P')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'P')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'P')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Podiatrists.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Podiatrists.{date}.txt', sep='|', index=False)
   
if 'Q' in df_dict:
    filtered_df_dict = df_dict['Q'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'Q')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'Q')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'Q')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Behavioral_Health.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Behavioral_Health.{date}.txt', sep='|', index=False)
   
if 'T' in df_dict:
    filtered_df_dict = df_dict['T'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'T')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'T')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'T')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_EPSDT.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_EPSDT.{date}.txt', sep='|', index=False)
 
if 'X' in df_dict:
    filtered_df_dict = df_dict['X'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'X')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'X')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'X')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_TRI.{date}.txt', sep='|', index=False)
 
if '3' in df_dict:
    filtered_df_dict = df_dict['3'].copy()
    filtered_df_dict = filtered_df_dict[(filtered_df_dict['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict,'3')
    Child_df=Child_Rate_Calculation(filtered_df_dict,'3')
    ER_df =ER_Rate_Calculation(filtered_df_dict,'3')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/MCal_Vision.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'MCal_Vision.{date}.txt', sep='|', index=False)
   
if '1' in df_dict:
    filtered_df_dict_1 = df_dict['1'][(~df_dict['1']['Proc_Code'].str.startswith('A0')) & (df_dict['1']['Rental_Rate'] == 0)].copy()
    filtered_df_dict_1 = filtered_df_dict_1[(filtered_df_dict_1['Basic_Rate'] > 0)]
    Basic_df=Basic_Rate_Calculation(filtered_df_dict_1,'1')
    Child_df=Child_Rate_Calculation(filtered_df_dict_1,'1')
    ER_df =ER_Rate_Calculation(filtered_df_dict_1,'1')
    final_df = pd.concat([Basic_df,Child_df,ER_df], ignore_index=True)
    final_df.to_csv(f'../Monthly_Output_Files/{date}/Mcal_Allied.{date}.txt', sep='|', index=False)
    #final_df.to_csv(f'Mcal_Allied.{date}.txt', sep='|', index=False)
 
    filtered_df_dict_2 = df_dict['1'][(~df_dict['1']['Proc_Code'].str.startswith('A0')) & (df_dict['1']['Rental_Rate'] > 0)].copy()
    Purchase_df = Purchase_Calculation(filtered_df_dict_2,'1')
    Rental_df = Rental_Calculation(filtered_df_dict_2,'1')
    final_df_2 = pd.concat([Purchase_df,Rental_df], ignore_index=True)
    final_df_2.to_csv(f'../Monthly_Output_Files/{date}/Mcal_DME.{date}.txt', sep='|', index=False)
    #final_df_2.to_csv(f'Mcal_DME.{date}.txt', sep='|', index=False)
print("code executed succesfully")
 
# End the timer
end_time = time.time()
 
# Calculate the time taken
time_taken = end_time - start_time
 
# Print the time taken
print("Time taken to execute the code is:", time_taken, "seconds")

FileNotFoundError: [Errno 2] No such file or directory: '../Augment_Codes/Augment Codes.xlsx'